version: '3.7'
## Adding Network
networks:
  mynetwork:
  ${COMPOSE_PROJECT_NAME}:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge  

services:
## Commenting out the db service for prod. Feel free to uncomment for local install 
#  db:
#    image: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASS}
#    volumes:
#      - ./db_data:/var/lib/mysql
#    ports:
#      - "3306:3306"   

  wordpress:
#    networks:
#     - ${COMPOSE_PROJECT_NAME} 
    build:
##    Put desired PHP version in env file
      dockerfile: .docker/wordpress/${PHP_VERSION}/apache/Dockerfile
      context: .
    ports:
      - "${APP_EXPOSED_PORT}:80"
#      - "443:443"
    volumes:
      - ./project:/var/www/html
      - ./uploads:/var/www/html/wp-content/uploads
#    depends_on:
#      - db
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_AUTH_KEY: ${AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${NONCE_SALT}
      WORDPRESS_DEBUG: ${WP_DEBUG}

# volumes:
#  db_data:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local  
#  project:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local
#  uploads:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local
