version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_test
      MYSQL_PASSWORD: 123456789

  drupal:
    image: drupal:latest
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_PORT=3306
      - DRUPAL_DB_NAME=drupal_db
      - DRUPAL_DB_USER=drupal_test
      - DRUPAL_DB_PASSWORD=123456789
