version: '3.7'
## Adding Network
networks:
  mynetwork:
  ${COMPOSE_PROJECT_NAME}:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge  

services:
## Commenting out the db service for prod. Feel free to uncomment for local install 
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_test
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./db_data:/var/lib/mysql
#    ports:
#      - "3306:3306"   

  drupal:
#    networks:
#     - ${COMPOSE_PROJECT_NAME} 
    build:
##    Put desired PHP version in .env file
      dockerfile: .docker/php8.2/apache-bullseye/Dockerfile
      context: .
    ports:
       - 8080:80
#      - "${APP_EXPOSED_PORT}:80"
#      - "443:443"
    #volumes:
    #  - ./project:/var/www/html
    # - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_PORT=3306
      - DRUPAL_DB_NAME=drupal_db
      - DRUPAL_DB_USER=drupal_test
      - DRUPAL_DB_PASSWORD=12356789

  phpmyadmin:
#    networks:
#     - ${COMPOSE_PROJECT_NAME}
    image: phpmyadmin/phpmyadmin:5.1
    ports:
         - 8000:80
#      - "${PHPMYADMIN_PORT}:80"
    #environment:
     # PMA_HOST: ${DB_HOST}
     # PMA_USER: ${DB_USER}
     # PMA_PASSWORD: ${DB_PASS}
    depends_on:
      - db

# volumes:
#  db_data:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local  
#  project:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local
#  uploads:
#    name: "${COMPOSE_PROJECT_NAME}_db_data"
#    driver: local
